// AUTO-GENERATED by scripts/sync-models.ts — do not edit by hand.
// Source: GET https://api.slng.ai/v1/catalog/models?service_type=stt
// Run `npm run sync-models` from the repo root to refresh.

import type { ModelGroup, LanguageOption } from "./models";

export const modelGroups: ModelGroup[] = [
  {
    "label": "SLNG / Deepgram",
    "options": [
      {
        "value": "slng/deepgram/nova:3-en",
        "label": "slng/deepgram/nova:3-en"
      },
      {
        "value": "slng/deepgram/nova:3-es",
        "label": "slng/deepgram/nova:3-es"
      },
      {
        "value": "slng/deepgram/nova:3-hi",
        "label": "slng/deepgram/nova:3-hi"
      },
      {
        "value": "slng/deepgram/nova:3-in",
        "label": "slng/deepgram/nova:3-in"
      },
      {
        "value": "slng/deepgram/nova:3-kn",
        "label": "slng/deepgram/nova:3-kn"
      },
      {
        "value": "slng/deepgram/nova:3-mr",
        "label": "slng/deepgram/nova:3-mr"
      },
      {
        "value": "slng/deepgram/nova:3-multi",
        "label": "slng/deepgram/nova:3-multi"
      },
      {
        "value": "slng/deepgram/nova:3-te",
        "label": "slng/deepgram/nova:3-te"
      }
    ]
  },
  {
    "label": "Deepgram",
    "options": [
      {
        "value": "deepgram/nova:3",
        "label": "deepgram/nova:3"
      },
      {
        "value": "deepgram/nova:3-medical",
        "label": "deepgram/nova:3-medical"
      }
    ]
  },
  {
    "label": "Reson8",
    "options": [
      {
        "value": "reson8/reson8stt:v1",
        "label": "reson8/reson8stt:v1"
      }
    ]
  },
  {
    "label": "Sarvam AI",
    "options": [
      {
        "value": "sarvam/saaras:v3",
        "label": "sarvam/saaras:v3"
      }
    ]
  },
  {
    "label": "Soniox",
    "options": [
      {
        "value": "soniox/speech-ai:rt-v3",
        "label": "soniox/speech-ai:rt-v3"
      },
      {
        "value": "soniox/speech-ai:rt-v4",
        "label": "soniox/speech-ai:rt-v4"
      }
    ]
  }
];

export const languagesByModel: Record<string, LanguageOption[]> = {
  "deepgram/nova:3": [
    {
      "value": "ar",
      "label": "Arabic"
    },
    {
      "value": "be",
      "label": "Belarusian"
    },
    {
      "value": "bg",
      "label": "Bulgarian"
    },
    {
      "value": "bn",
      "label": "Bengali"
    },
    {
      "value": "bs",
      "label": "Bosnian"
    },
    {
      "value": "ca",
      "label": "Catalan"
    },
    {
      "value": "cs",
      "label": "Czech"
    },
    {
      "value": "da",
      "label": "Danish"
    },
    {
      "value": "el",
      "label": "Greek"
    },
    {
      "value": "en",
      "label": "English"
    },
    {
      "value": "et",
      "label": "Estonian"
    },
    {
      "value": "fa",
      "label": "Persian"
    },
    {
      "value": "fi",
      "label": "Finnish"
    },
    {
      "value": "fr",
      "label": "French"
    },
    {
      "value": "he",
      "label": "Hebrew"
    },
    {
      "value": "hi",
      "label": "Hindi"
    },
    {
      "value": "hr",
      "label": "Croatian"
    },
    {
      "value": "hu",
      "label": "Hungarian"
    },
    {
      "value": "id",
      "label": "Indonesian"
    },
    {
      "value": "it",
      "label": "Italian"
    },
    {
      "value": "ja",
      "label": "Japanese"
    },
    {
      "value": "kn",
      "label": "Kannada"
    },
    {
      "value": "ko",
      "label": "Korean"
    },
    {
      "value": "lt",
      "label": "Lithuanian"
    },
    {
      "value": "lv",
      "label": "Latvian"
    },
    {
      "value": "mk",
      "label": "Macedonian"
    },
    {
      "value": "mr",
      "label": "Marathi"
    },
    {
      "value": "ms",
      "label": "Malay"
    },
    {
      "value": "nl",
      "label": "Dutch"
    },
    {
      "value": "no",
      "label": "Norwegian"
    },
    {
      "value": "pl",
      "label": "Polish"
    },
    {
      "value": "pt",
      "label": "Portuguese"
    },
    {
      "value": "ro",
      "label": "Romanian"
    },
    {
      "value": "ru",
      "label": "Russian"
    },
    {
      "value": "sk",
      "label": "Slovak"
    },
    {
      "value": "sl",
      "label": "Slovenian"
    },
    {
      "value": "sr",
      "label": "Serbian"
    },
    {
      "value": "sv",
      "label": "Swedish"
    },
    {
      "value": "ta",
      "label": "Tamil"
    },
    {
      "value": "te",
      "label": "Telugu"
    },
    {
      "value": "th",
      "label": "Thai"
    },
    {
      "value": "tl",
      "label": "Tagalog"
    },
    {
      "value": "tr",
      "label": "Turkish"
    },
    {
      "value": "uk",
      "label": "Ukrainian"
    },
    {
      "value": "ur",
      "label": "Urdu"
    },
    {
      "value": "vi",
      "label": "Vietnamese"
    },
    {
      "value": "zh",
      "label": "Chinese"
    }
  ],
  "slng/deepgram/nova:3-in": [
    {
      "value": "id",
      "label": "Indonesian"
    }
  ],
  "slng/deepgram/nova:3-kn": [
    {
      "value": "kn",
      "label": "Kannada"
    }
  ],
  "slng/deepgram/nova:3-mr": [
    {
      "value": "mr",
      "label": "Marathi"
    }
  ],
  "deepgram/nova:3-medical": [
    {
      "value": "en",
      "label": "English"
    }
  ],
  "slng/deepgram/nova:3-es": [
    {
      "value": "es",
      "label": "Spanish"
    }
  ],
  "slng/deepgram/nova:3-te": [
    {
      "value": "te",
      "label": "Telugu"
    }
  ],
  "reson8/reson8stt:v1": [
    {
      "value": "en",
      "label": "English"
    }
  ],
  "sarvam/saaras:v3": [
    {
      "value": "as",
      "label": "Assamese"
    },
    {
      "value": "bm",
      "label": "Bambara"
    },
    {
      "value": "bn",
      "label": "Bengali"
    },
    {
      "value": "en",
      "label": "English"
    },
    {
      "value": "gu",
      "label": "Gujarati"
    },
    {
      "value": "hi",
      "label": "Hindi"
    },
    {
      "value": "kn",
      "label": "Kannada"
    },
    {
      "value": "ml",
      "label": "Malayalam"
    },
    {
      "value": "mr",
      "label": "Marathi"
    },
    {
      "value": "ne",
      "label": "Nepali"
    },
    {
      "value": "te",
      "label": "Telugu"
    },
    {
      "value": "ur",
      "label": "Urdu"
    }
  ],
  "soniox/speech-ai:rt-v3": [
    {
      "value": "am",
      "label": "Amharic"
    },
    {
      "value": "ar",
      "label": "Arabic"
    },
    {
      "value": "ay",
      "label": "Aymara"
    },
    {
      "value": "az",
      "label": "Azerbaijani"
    },
    {
      "value": "be",
      "label": "Belarusian"
    },
    {
      "value": "bg",
      "label": "Bulgarian"
    },
    {
      "value": "bn",
      "label": "Bengali"
    },
    {
      "value": "bs",
      "label": "Bosnian"
    },
    {
      "value": "ca",
      "label": "Catalan"
    },
    {
      "value": "da",
      "label": "Danish"
    },
    {
      "value": "de",
      "label": "German"
    },
    {
      "value": "el",
      "label": "Greek"
    },
    {
      "value": "en",
      "label": "English"
    },
    {
      "value": "es",
      "label": "Spanish"
    },
    {
      "value": "et",
      "label": "Estonian"
    },
    {
      "value": "eu",
      "label": "Basque"
    },
    {
      "value": "fi",
      "label": "Finnish"
    },
    {
      "value": "fr",
      "label": "French"
    },
    {
      "value": "ga",
      "label": "Irish"
    },
    {
      "value": "gl",
      "label": "Galician"
    },
    {
      "value": "gn",
      "label": "Guarani"
    },
    {
      "value": "he",
      "label": "Hebrew"
    },
    {
      "value": "hi",
      "label": "Hindi"
    },
    {
      "value": "hr",
      "label": "Croatian"
    },
    {
      "value": "hy",
      "label": "Armenian"
    },
    {
      "value": "id",
      "label": "Indonesian"
    },
    {
      "value": "is",
      "label": "Icelandic"
    },
    {
      "value": "it",
      "label": "Italian"
    },
    {
      "value": "ja",
      "label": "Japanese"
    },
    {
      "value": "ka",
      "label": "Georgian"
    },
    {
      "value": "kk",
      "label": "Kazakh"
    },
    {
      "value": "kn",
      "label": "Kannada"
    },
    {
      "value": "ko",
      "label": "Korean"
    },
    {
      "value": "ku",
      "label": "Kurdish"
    },
    {
      "value": "la",
      "label": "Latin"
    },
    {
      "value": "lb",
      "label": "Luxembourgish"
    },
    {
      "value": "lt",
      "label": "Lithuanian"
    },
    {
      "value": "mr",
      "label": "Marathi"
    },
    {
      "value": "sa",
      "label": "Sanskrit"
    },
    {
      "value": "sw",
      "label": "Swahili"
    },
    {
      "value": "zh",
      "label": "Chinese"
    }
  ],
  "slng/deepgram/nova:3-en": [
    {
      "value": "en",
      "label": "English"
    }
  ],
  "slng/deepgram/nova:3-multi": [
    {
      "value": "ar",
      "label": "Arabic"
    },
    {
      "value": "de",
      "label": "German"
    },
    {
      "value": "en",
      "label": "English"
    },
    {
      "value": "es",
      "label": "Spanish"
    },
    {
      "value": "fr",
      "label": "French"
    },
    {
      "value": "hi",
      "label": "Hindi"
    },
    {
      "value": "it",
      "label": "Italian"
    },
    {
      "value": "ja",
      "label": "Japanese"
    },
    {
      "value": "nl",
      "label": "Dutch"
    },
    {
      "value": "pt",
      "label": "Portuguese"
    },
    {
      "value": "ru",
      "label": "Russian"
    }
  ],
  "soniox/speech-ai:rt-v4": [
    {
      "value": "am",
      "label": "Amharic"
    },
    {
      "value": "ar",
      "label": "Arabic"
    },
    {
      "value": "ay",
      "label": "Aymara"
    },
    {
      "value": "az",
      "label": "Azerbaijani"
    },
    {
      "value": "be",
      "label": "Belarusian"
    },
    {
      "value": "bg",
      "label": "Bulgarian"
    },
    {
      "value": "bn",
      "label": "Bengali"
    },
    {
      "value": "bs",
      "label": "Bosnian"
    },
    {
      "value": "ca",
      "label": "Catalan"
    },
    {
      "value": "co",
      "label": "Corsican"
    },
    {
      "value": "da",
      "label": "Danish"
    },
    {
      "value": "de",
      "label": "German"
    },
    {
      "value": "el",
      "label": "Greek"
    },
    {
      "value": "en",
      "label": "English"
    },
    {
      "value": "es",
      "label": "Spanish"
    },
    {
      "value": "et",
      "label": "Estonian"
    },
    {
      "value": "eu",
      "label": "Basque"
    },
    {
      "value": "fi",
      "label": "Finnish"
    },
    {
      "value": "fr",
      "label": "French"
    },
    {
      "value": "gl",
      "label": "Galician"
    },
    {
      "value": "gn",
      "label": "Guarani"
    },
    {
      "value": "he",
      "label": "Hebrew"
    },
    {
      "value": "hi",
      "label": "Hindi"
    },
    {
      "value": "hr",
      "label": "Croatian"
    },
    {
      "value": "id",
      "label": "Indonesian"
    },
    {
      "value": "it",
      "label": "Italian"
    },
    {
      "value": "ja",
      "label": "Japanese"
    },
    {
      "value": "ka",
      "label": "Georgian"
    },
    {
      "value": "kn",
      "label": "Kannada"
    },
    {
      "value": "ko",
      "label": "Korean"
    },
    {
      "value": "ku",
      "label": "Kurdish"
    },
    {
      "value": "lt",
      "label": "Lithuanian"
    },
    {
      "value": "lv",
      "label": "Latvian"
    },
    {
      "value": "mn",
      "label": "Mongolian"
    },
    {
      "value": "mr",
      "label": "Marathi"
    },
    {
      "value": "my",
      "label": "Burmese"
    },
    {
      "value": "ne",
      "label": "Nepali"
    },
    {
      "value": "nl",
      "label": "Dutch"
    },
    {
      "value": "no",
      "label": "Norwegian"
    },
    {
      "value": "pa",
      "label": "Punjabi"
    },
    {
      "value": "pl",
      "label": "Polish"
    },
    {
      "value": "pt",
      "label": "Portuguese"
    },
    {
      "value": "ro",
      "label": "Romanian"
    },
    {
      "value": "ru",
      "label": "Russian"
    },
    {
      "value": "sk",
      "label": "Slovak"
    },
    {
      "value": "sl",
      "label": "Slovenian"
    },
    {
      "value": "so",
      "label": "Somali"
    },
    {
      "value": "sv",
      "label": "Swedish"
    },
    {
      "value": "ta",
      "label": "Tamil"
    },
    {
      "value": "te",
      "label": "Telugu"
    },
    {
      "value": "uk",
      "label": "Ukrainian"
    },
    {
      "value": "vi",
      "label": "Vietnamese"
    },
    {
      "value": "zh",
      "label": "Chinese"
    }
  ],
  "slng/deepgram/nova:3-hi": [
    {
      "value": "en",
      "label": "English"
    },
    {
      "value": "hi",
      "label": "Hindi"
    }
  ]
};

export const languageOptions: LanguageOption[] = [
  {
    "value": "am",
    "label": "Amharic"
  },
  {
    "value": "ar",
    "label": "Arabic"
  },
  {
    "value": "hy",
    "label": "Armenian"
  },
  {
    "value": "as",
    "label": "Assamese"
  },
  {
    "value": "ay",
    "label": "Aymara"
  },
  {
    "value": "az",
    "label": "Azerbaijani"
  },
  {
    "value": "bm",
    "label": "Bambara"
  },
  {
    "value": "eu",
    "label": "Basque"
  },
  {
    "value": "be",
    "label": "Belarusian"
  },
  {
    "value": "bn",
    "label": "Bengali"
  },
  {
    "value": "bs",
    "label": "Bosnian"
  },
  {
    "value": "bg",
    "label": "Bulgarian"
  },
  {
    "value": "my",
    "label": "Burmese"
  },
  {
    "value": "ca",
    "label": "Catalan"
  },
  {
    "value": "zh",
    "label": "Chinese"
  },
  {
    "value": "co",
    "label": "Corsican"
  },
  {
    "value": "hr",
    "label": "Croatian"
  },
  {
    "value": "cs",
    "label": "Czech"
  },
  {
    "value": "da",
    "label": "Danish"
  },
  {
    "value": "nl",
    "label": "Dutch"
  },
  {
    "value": "en",
    "label": "English"
  },
  {
    "value": "et",
    "label": "Estonian"
  },
  {
    "value": "fi",
    "label": "Finnish"
  },
  {
    "value": "fr",
    "label": "French"
  },
  {
    "value": "gl",
    "label": "Galician"
  },
  {
    "value": "ka",
    "label": "Georgian"
  },
  {
    "value": "de",
    "label": "German"
  },
  {
    "value": "el",
    "label": "Greek"
  },
  {
    "value": "gn",
    "label": "Guarani"
  },
  {
    "value": "gu",
    "label": "Gujarati"
  },
  {
    "value": "he",
    "label": "Hebrew"
  },
  {
    "value": "hi",
    "label": "Hindi"
  },
  {
    "value": "hu",
    "label": "Hungarian"
  },
  {
    "value": "is",
    "label": "Icelandic"
  },
  {
    "value": "id",
    "label": "Indonesian"
  },
  {
    "value": "ga",
    "label": "Irish"
  },
  {
    "value": "it",
    "label": "Italian"
  },
  {
    "value": "ja",
    "label": "Japanese"
  },
  {
    "value": "kn",
    "label": "Kannada"
  },
  {
    "value": "kk",
    "label": "Kazakh"
  },
  {
    "value": "ko",
    "label": "Korean"
  },
  {
    "value": "ku",
    "label": "Kurdish"
  },
  {
    "value": "la",
    "label": "Latin"
  },
  {
    "value": "lv",
    "label": "Latvian"
  },
  {
    "value": "lt",
    "label": "Lithuanian"
  },
  {
    "value": "lb",
    "label": "Luxembourgish"
  },
  {
    "value": "mk",
    "label": "Macedonian"
  },
  {
    "value": "ms",
    "label": "Malay"
  },
  {
    "value": "ml",
    "label": "Malayalam"
  },
  {
    "value": "mr",
    "label": "Marathi"
  },
  {
    "value": "mn",
    "label": "Mongolian"
  },
  {
    "value": "ne",
    "label": "Nepali"
  },
  {
    "value": "no",
    "label": "Norwegian"
  },
  {
    "value": "fa",
    "label": "Persian"
  },
  {
    "value": "pl",
    "label": "Polish"
  },
  {
    "value": "pt",
    "label": "Portuguese"
  },
  {
    "value": "pa",
    "label": "Punjabi"
  },
  {
    "value": "ro",
    "label": "Romanian"
  },
  {
    "value": "ru",
    "label": "Russian"
  },
  {
    "value": "sa",
    "label": "Sanskrit"
  },
  {
    "value": "sr",
    "label": "Serbian"
  },
  {
    "value": "sk",
    "label": "Slovak"
  },
  {
    "value": "sl",
    "label": "Slovenian"
  },
  {
    "value": "so",
    "label": "Somali"
  },
  {
    "value": "es",
    "label": "Spanish"
  },
  {
    "value": "sw",
    "label": "Swahili"
  },
  {
    "value": "sv",
    "label": "Swedish"
  },
  {
    "value": "tl",
    "label": "Tagalog"
  },
  {
    "value": "ta",
    "label": "Tamil"
  },
  {
    "value": "te",
    "label": "Telugu"
  },
  {
    "value": "th",
    "label": "Thai"
  },
  {
    "value": "tr",
    "label": "Turkish"
  },
  {
    "value": "uk",
    "label": "Ukrainian"
  },
  {
    "value": "ur",
    "label": "Urdu"
  },
  {
    "value": "vi",
    "label": "Vietnamese"
  }
];
