// AUTO-GENERATED by scripts/sync-models.ts — do not edit by hand.
// Source: GET https://api.slng.ai/v1/catalog/models?service_type=tts
// Run `npm run sync-models` from the repo root to refresh.

import type { ModelGroup, VoiceGroup } from "./models";

export const modelGroups: ModelGroup[] = [
  {
    "label": "SLNG / Deepgram",
    "options": [
      {
        "value": "slng/deepgram/aura:2-en",
        "label": "slng/deepgram/aura:2-en"
      }
    ]
  },
  {
    "label": "SLNG / Fish Audio",
    "options": [
      {
        "value": "slng/fish/tts:s2.1-pro",
        "label": "slng/fish/tts:s2.1-pro"
      }
    ]
  },
  {
    "label": "SLNG / Inworld",
    "options": [
      {
        "value": "slng/inworld/max:1.5",
        "label": "slng/inworld/max:1.5"
      }
    ]
  },
  {
    "label": "Cartesia",
    "options": [
      {
        "value": "cartesia/sonic:3",
        "label": "cartesia/sonic:3",
        "wsOnly": true
      },
      {
        "value": "cartesia/sonic:3.5",
        "label": "cartesia/sonic:3.5",
        "wsOnly": true
      }
    ]
  },
  {
    "label": "Deepgram",
    "options": [
      {
        "value": "deepgram/aura:2",
        "label": "deepgram/aura:2"
      }
    ]
  },
  {
    "label": "Fish Audio",
    "options": [
      {
        "value": "fish/tts:s2-pro",
        "label": "fish/tts:s2-pro"
      },
      {
        "value": "fish/tts:s2.1-pro",
        "label": "fish/tts:s2.1-pro"
      }
    ]
  },
  {
    "label": "Kugel Audio",
    "options": [
      {
        "value": "kugelaudio/kugel:2",
        "label": "kugelaudio/kugel:2",
        "wsOnly": true
      }
    ]
  },
  {
    "label": "MurfAI",
    "options": [
      {
        "value": "murf/murftts:falcon",
        "label": "murf/murftts:falcon",
        "wsOnly": true
      }
    ]
  },
  {
    "label": "Sarvam AI",
    "options": [
      {
        "value": "sarvam/bulbul:v3",
        "label": "sarvam/bulbul:v3"
      }
    ]
  },
  {
    "label": "Soniox",
    "options": [
      {
        "value": "soniox/tts-rt:v1",
        "label": "soniox/tts-rt:v1"
      }
    ]
  }
];

export const voicesByModel: Record<string, VoiceGroup[]> = {};
